<?php
/**
 * @package WP Simple Booking Calendar
 *
 * Copyright (c) 2010 Lennart Visscher
 */
?>

<div id="sbc-wrapper" class="wrap">
	<div id="icon-options-general" class="icon32"><br /></div>
	<h2><?php esc_html_e('WP Simple Booking Calendar', 'sbc') ?> 
	<?php if (!is_array($this->calendar) || count($this->calendar) == 0): ?>
		<a class="button add-new-h2" href="<?php echo esc_url($this->controllerUrl) ?>&amp;action=add"><?php esc_html_e('Add New', 'sbc') ?></a>
	<?php endif; ?>
	</h2>
	
	<?php if (is_array($this->calendar) && count($this->calendar)): ?>
		<table class="widefat post fixed" cellspacing="0">
			<thead>
				<tr class="alt">
					<th class="manage-column column-name"><?php esc_html_e('Calendar Name', 'sbc') ?></th>
					<th class="manage-column column-created"><?php esc_html_e('Created', 'sbc') ?></th>
					<th class="manage-column column-modified"><?php esc_html_e('Modified', 'sbc') ?></th>
				</tr>
			</thead>
			<tbody>
				<tr valign="top">
					<td class="post-title column-title">
						<strong><a title="<?php esc_attr_e('Edit', 'sbc') ?> ‟<?php echo esc_attr($this->calendar['calendarName']) ?>”" href="<?php echo esc_url($this->controllerUrl) ?>&amp;action=edit" class="row-title"><?php echo esc_html($this->calendar['calendarName']) ?></a></strong>
						<div class="row-actions">
							<span class="edit"><a title="<?php esc_attr_e('Edit this calendar', 'sbc') ?>" href="<?php echo esc_url($this->controllerUrl) ?>&amp;action=edit"><?php esc_html_e('Edit', 'sbc') ?></a> | </span>
							<span class="trash"><a title="<?php esc_attr_e('Are you sure you want to delete this calendar?', 'sbc') ?>" href="<?php echo esc_url($this->controllerUrl) ?>&amp;action=delete" class="submitdelete"><?php esc_html_e('Delete', 'sbc') ?></a></span>
						</div>
					</td>
					<td class="street column-created">
						<?php echo esc_html(date($this->dateFormat, $this->calendar['dateCreated'])) ?><br/>
						<?php echo esc_html(date($this->timeFormat, $this->calendar['dateCreated'])) ?>
					</td>
					<td class="street column-modified">
						<?php echo esc_html(date($this->dateFormat, $this->calendar['dateModified'])) ?><br/>
						<?php echo esc_html(date($this->timeFormat, $this->calendar['dateModified'])) ?>
					</td>
				</tr>
			</tbody>
		</table>
	<div class="updated">
		<span style="color: #21759B;">Get the full version</span>
		<p style="font-size: 12px;">- Create an unlimited number of calendars<br />
		- Show a legend near the calendar<br />
		- Two month view<br />
		- Only $25<br />	
		- 100% money back guarantee</p>
		<p><a class="button-secondary" href="http://www.simplebookingcalendar.com/download-full-version/" title="">Add To Cart</a></p>
	</div>
	<?php else: ?>
		<p><?php esc_html_e('No calendar found.', 'sbc') ?></p>
	<?php endif ?>
</div>